import {
  BookOpen,
  Users,
  Building2,
  Activity,
  Settings,
  FileText,
  Video,
  Newspaper,
  MessageSquare,
  HelpCircle,
  Library,
  TrendingUp,
  Star,
  ClipboardList,
  Shield,
  AlertCircle,
  Award,
  CreditCard,
  DollarSign,
  FileBarChart,
  MapPin,
  Bug,
  CircleUser,
  BadgeDollarSign,
  School,
  Briefcase,
  GraduationCap,
  UserCheck,
  Crown,
  Key,
  MessageCircle,
  Target,
  PhoneCall,
  UserPlus,
  Trophy,
  Folder,
  Quote,
  Users2,
  Building,
  TrophyIcon,
  FolderOpen,
  FileSpreadsheet,
  UserCog,
} from "lucide-react";

const allIcons = [
  BookOpen,
  Users,
  Building2,
  Activity,
  Settings,
  FileText,
  Video,
  Newspaper,
  MessageSquare,
  HelpCircle,
  Library,
  TrendingUp,
  Star,
  ClipboardList,
  Shield,
  AlertCircle,
  Award,
  CreditCard,
  DollarSign,
  FileBarChart,
  MapPin,
  Bug,
  CircleUser,
  BadgeDollarSign,
  School,
  Briefcase,
  GraduationCap,
  UserCheck,
  Crown,
  Key,
  MessageCircle,
  Target,
  PhoneCall,
  UserPlus,
  Trophy,
  Folder,
  Quote,
  Users2,
  Building,
  TrophyIcon,
  FolderOpen,
  FileSpreadsheet,
  UserCog,
];

let usedIconIndex = 0;
const getNextIcon = () => allIcons[usedIconIndex++ % allIcons.length];

export const SidebarData = {
  user: {
    name: "Karn",
    email: "Karan@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  sections: [
    // Platform Desk
    {
      title: "Platform",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Platform Desk",
          url: "/desk/platform/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Recent Activities",
          url: "/desk/platform/activities",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Assessment",
          url: "/desk/platform/assessment",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Sessions",
          icon: getNextIcon(),
          url: "/desk/platform/products/sessions",
          isActive: true,
        },
        {
          title: "Masterclasses",
          url: "/desk/platform/products/masterclasses",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Events",
          url: "/desk/platform/events",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Courses",
          url: "/desk/platform/courses",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Contribute",
          url: "/desk/platform/contribute",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Access Code",
          url: "/desk/platform/plans/access-code",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Manage Commissions",
          url: "/desk/platform/plans/consultants-premium",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Forms",
          url: "/desk/platform/forms",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Desk IAM",
          url: "/desk/platform/desk-iam",
          icon: getNextIcon(),
          isActive: true,
        },
      ],
    },
    // Review Desk
    {
      title: "Review",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Review Desk",
          url: "/desk/review/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Review Pool",
          url: "/desk/review/pool",
          icon: getNextIcon(),
          isActive: true,
        },
        // {
        //   title: "Coaches",
        //   url: "/desk/review/coaches",
        //   icon: getNextIcon(),
        // },
        // {
        //   title: "Organisations",
        //   url: "/desk/review/organisations",
        //   icon: getNextIcon(),
        // },
        // {
        //   title: "Channel Partners",
        //   url: "/desk/review/channel-partners",
        //   icon: getNextIcon(),
        // },
        // {
        //   title: "Libraries",
        //   url: "/desk/review/libraries",
        //   icon: getNextIcon(),
        // },
        // {
        //   title: "Map Listing",
        //   url: "/desk/review/map-listing",
        //   icon: getNextIcon(),
        // },
        // {
        //   title: "Custom Inputs",
        //   url: "/desk/review/custom-inputs",
        //   icon: getNextIcon(),
        // },
        {
          title: "Follow Ups",
          url: "/desk/review/follow-ups",
          icon: getNextIcon(),
          isActive: true,
        },
      ],
    },
    // Relations Desk
    {
      title: "Relations",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Relations Desk",
          url: "/desk/relation/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "My Pipeline",
          url: "/desk/relation/pipeline",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Pool",
          url: "/desk/relation/pool",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Leads",
          icon: getNextIcon(),
          url: "#",
          isCollapsible: true,
          items: [
            {
              title: "Explorers",
              url: "/desk/relation/leads/explorers",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Coaches",
              url: "/desk/relation/leads/coaches",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Organisations",
              url: "/desk/relation/leads/organisations",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Channel Partner",
              url: "/desk/relation/leads/channel-partner",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Partnerships Requests",
              url: "/desk/relation/leads/partnerships-requests",
              icon: getNextIcon(),
              isActive: true,
            },
          ],
        },
        {
          title: "Cases",
          icon: getNextIcon(),
          url: "#",
          isCollapsible: true,
          items: [
            {
              title: "Problems",
              url: "/desk/relation/cases/problems",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Bugs",
              url: "/desk/relation/cases/bugs",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Abuses",
              url: "/desk/relation/cases/abuses",
              icon: getNextIcon(),
              isActive: true,
            },
          ],
        },
        {
          title: "Explorers",
          url: "/desk/relation/explorers",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Coaches",
          url: "/desk/relation/coaches",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Organisations",
          icon: getNextIcon(),
          url: "/desk/relation/organisations",
          isActive: true,
          // isCollapsible: true,
          // items: [
          //   {
          //     title: "Institutes",
          //     url: "/desk/relation/organisations/institutes",
          //     icon: getNextIcon(),
          //   },
          //   {
          //     title: "Schools",
          //     url: "/desk/relation/organisations/schools",
          //     icon: getNextIcon(),
          //   },
          //   {
          //     title: "Colleges",
          //     url: "/desk/relation/organisations/colleges",
          //     icon: getNextIcon(),
          //   },
          //   {
          //     title: "Companies",
          //     url: "/desk/relation/organisations/companies",
          //     icon: getNextIcon(),
          //   },
          //   {
          //     title: "Universities",
          //     url: "/desk/relation/organisations/universities",
          //     icon: getNextIcon(),
          //   },
          //   {
          //     title: "NGO's",
          //     url: "/desk/relation/organisations/ngos",
          //     icon: getNextIcon(),
          //   },
          // ],
        },
        {
          title: "My Accounts",
          url: "/desk/relation/my-accounts",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Leaderboard",
          url: "/desk/relation/leaderboard",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Add Lead Flow",
          url: "/desk/relation/add-lead-flow",
          icon: getNextIcon(),
          isActive: true,
        },
      ],
    },
    // Digital Desk
    {
      title: "Digital",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Digital Desk",
          url: "/desk/digital/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Campaigns",
          url: "/desk/digital/campaigns",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Surveys",
          url: "/desk/digital/surveys",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "CMS",
          icon: getNextIcon(),
          url: "#",
          isCollapsible: true,
          items: [
            {
              title: "Insights",
              url: "/desk/digital/cms/insights",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Video",
              url: "/desk/digital/cms/video",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "FAQs",
              url: "/desk/digital/cms/faqs",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Help Articles",
              url: "/desk/digital/cms/help-articles",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "In the News",
              url: "/desk/digital/cms/in-the-news",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Testimonials",
              url: "/desk/digital/cms/testimonials",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Teams Directory",
              url: "/desk/digital/cms/teams-directory",
              icon: getNextIcon(),
              isActive: true,
            },
          ],
        },
        {
          title: "Libraries",
          icon: getNextIcon(),
          url: "#",
          isCollapsible: true,
          items: [
            {
              title: "Exams",
              url: "/desk/digital/libraries/exams",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Careers",
              url: "/desk/digital/libraries/careers",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Degrees",
              url: "/desk/digital/libraries/degrees",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Courses",
              url: "/desk/digital/libraries/courses",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Scholarships",
              url: "/desk/digital/libraries/scholarships",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Skills",
              url: "/desk/digital/libraries/skills",
              icon: getNextIcon(),
              isActive: true,
            },
          ],
        },
        {
          title: "Engage",
          icon: getNextIcon(),
          url: "#",
          isCollapsible: true,
          items: [
            {
              title: "Review",
              url: "/desk/digital/engage/review",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Comments",
              url: "/desk/digital/engage/comments",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Feedback",
              url: "/desk/digital/engage/feedback",
              icon: getNextIcon(),
              isActive: true,
            },
            {
              title: "Helpful",
              url: "/desk/digital/engage/helpful",
              icon: getNextIcon(),
              isActive: false,
            },
          ],
        },
        {
          title: "File Manager",
          url: "/desk/digital/file-manager",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Meta Information",
          url: "/desk/digital/meta-information",
          icon: getNextIcon(),
          isActive: false,
        },
      ],
    },
    // Finance Desk
    {
      title: "Finance",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Finance Desk",
          url: "/desk/finance/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Payments",
          url: "/desk/finance/payments",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Commissions",
          url: "/desk/finance/commissions",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Withdrawal",
          url: "/desk/finance/withdrawal",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Payouts",
          url: "/desk/finance/payouts",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Platform",
          url: "/desk/finance/platform",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Earnings",
          url: "/desk/finance/earnings",
          icon: getNextIcon(),
        },
        {
          title: "Reports",
          url: "/desk/finance/reports",
          icon: getNextIcon(),
          isActive: true,
        },
      ],
    },
    // DevOps Desk
    {
      title: "DevOps",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "Devops Desk",
          url: "/desk/devops/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "My Cases",
          url: "/desk/devops/my-cases",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Cases",
          url: "/desk/devops/cases",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Leaderboard",
          url: "/desk/devops/leaderboard",
          icon: getNextIcon(),
          isActive: false,
        },
      ],
    },
    // HR Desk
    {
      title: "HRMS",
      icon: getNextIcon(),
      isHeading: true,
      items: [
        {
          title: "HR Desk",
          url: "/desk/hr/desk",
          icon: getNextIcon(),
          isActive: false,
        },
        {
          title: "Follow Ups",
          url: "/desk/hr/follow-ups",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Current Openings",
          url: "/desk/hr/current-opening",
          icon: getNextIcon(),
          isActive: true,
        },
        {
          title: "Job Application",
          url: "/desk/hr/job-application",
          icon: getNextIcon(),
          isActive: true,
        },
      ],
    },
  ],
};
